export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAIL = 'FETCH_POKEMONS_FAIL';

export const FETCH_POKEMON = 'FETCH_POKEMON';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SEARCH_POKEMONS = 'SEARCH_POKEMONS';

export const LOADING_POKEMONS = 'LOADING_POKEMONS';
