export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAIL = 'FETCH_POKEMONS_FAIL';

export const FETCH_POKEMON = 'FETCH_POKEMON';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SEARCH_POKEMONS = 'SEARCH_POKEMONS';

export const SET_SORT_OPTION = 'SET_SORT_OPTION';
export const SORT_POKEMONS_BY_NAME = 'SORT_POKEMONS_BY_NAME';
export const SORT_POKEMONS_BY_ID = 'SORT_POKEMONS_BY_ID';

export const LOADING_POKEMONS = 'LOADING_POKEMONS';
